# SPDX-License-Identifier: AGPL-3.0-or-later

name: Update Contrib and Patreons in credits
concurrency: commit_action
on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 0 * * 0

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  get_credits:
    runs-on: ubuntu-latest
    if: github.repository == 'Reserve-Station/Reserve-Station'

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: "${{ vars.CHANGELOG_BRANCH }}"

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Get contributors
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: Tools/dump_github_contributors.ps1 > Resources/Credits/GitHub.txt

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Commit Changelog
        run: |
          git add Resources/Credits/GitHub.txt
          git commit -m "${{ vars.CREDITS_MESSAGE }} (${{ env.NOW }})"
          git push
        shell: bash
        continue-on-error: true
